---
include:
  - board: nice_nano
    shield: Lily58_L oled_adapter_pro_micro_128x32 nice_oled
  - board: nice_nano
    shield: Lily58_R oled_adapter_pro_micro_128x32 nice_oled
  - board: nice_nano
    shield: settings_reset
