manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: PandaKBLab
      url-base: https://github.com/PandaKBLab
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-for-PandaKB
      remote: PandaKBLab
      revision: PandaKB_Lily58
  self:
    path: config
